---
sidebar: sidebar 
permalink: add-components-to-search-criteria.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, Active IQ, Interop, Advisor, tool 
summary: 検索テキストボックスまたは拡張検索を使用して、検索条件にコンポーネントを追加できます。 
---
= 検索条件にコンポーネントを追加
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
検索テキストボックスまたは*拡張検索*を使用して、検索条件にコンポーネントを追加できます。

.タスクの内容
検索条件に追加するコンポーネントがわかっている場合は、検索テキストボックスにコンポーネント名を入力できます。検索条件に追加するコンポーネントがわからない場合は、*拡張検索*を使用できます。

検索条件に含まれる構成部品をクリアするには、右上隅の*すべてクリア*をクリックします。

.手順
. Interoperability Matrix Toolのホームページで、検索テキストボックスにコンポーネント名を入力してコンポーネントに一致するコンポーネントを表示します。
+
.. [追加（Add）]*をクリックして、構成要素を検索条件に含めます。
.. 複数のカテゴリのコンポーネントを検索条件に含めるには、*[追加]*をクリックします。
.. [すべての一致を表示]*をクリックすると、IMTは*[詳細検索]*を表示し、これを使用して検索条件にさらに多くのコンポーネントを含めることができます。


. オプション。[拡張検索（Advanced Search）]*を使用して、構成要素を検索条件に含めることができます。
+
.. [詳細検索]*をクリックします。
.. [詳細検索]ウィンドウで、左側のペインからカテゴリまたはソリューションを選択します。
.. 右側のペインで、検索条件に追加するコンポーネントを特定し、*[追加]*をクリックします。
.. [詳細検索]ウィンドウにキーワードを入力します。




検索オプションとしてキーワードを活動化できます。活動化されている場合は、それらの行に関連付けられているキーワードを使用して1つ以上の行を検索できます。また、*拡張検索*ウィンドウ内の検索テキストボックスを使用して、特定のコンポーネントを検索することもできます。[拡張検索（Advanced Search）]*を使用して追加された構成要素を削除するには、右ペインの*[削除（Remove）]*をクリックします。



== 結果

検索条件に構成要素を含めると、右ペインの*検索条件*の下に構成要素が表示されます。
