---
sidebar: sidebar 
permalink: index.html 
keywords: interoperability matrix tool, imt, ONTAP SAN Host Simplified, 
summary: NetApp Interoperability Matrix Tool（IMT）はWebベースのアプリケーションです。IMTでは、NetAppで指定された標準および要件を満たすNetApp製品およびコンポーネントの構成を検索できます。 
---
= Interoperability Matrix Toolの概要
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Interoperability Matrix Tool（IMT）はWebベースのアプリケーションです。IMTでは、NetAppで指定された標準および要件を満たすNetApp製品およびコンポーネントの構成を検索できます。IMTは、構成のリポジトリを管理し、サポートされている構成情報に簡単にアクセスできる使いやすいインターフェイスを提供します。

IMTには、NetAppサポートサイトから次のいずれかの標準ブラウザを使用してアクセスできます。

* Windowsの場合：
+
** Chrome NおよびN-1
** Mozilla Firefox NおよびN-1
+

NOTE: Nは最新バージョンを表します。

** Internet Explorer 11およびEdge


* Macの場合：
+
** Chrome NおよびN-1
** Mozilla Firefox NおよびN-1
** Safari 8以降


+

NOTE: Interoperability Matrix Toolでは、特定のユースケースを簡易化するために、条件付きのURLリンクを設定できます。別のツールのリンクをクリックしてIMTを開くと、ソリューションと特定のコンポーネントが事前に選択された状態で、ホームページではなくプレイグラウンドページが表示される場合があります。





== Interoperability Matrix Toolを使用する

Interoperability Matrix Tool（IMT）は、Webベースのアプリケーションです。さまざまなソリューション、構成、コンポーネント、カテゴリを使用して、製品の互換性を検索できます。

このツールは、簡単に操作してわかりやすくするために、*条件の入力*、*検索条件の絞り込み*、*結果*の3つのページに分かれています。最初のページで検索条件を入力する必要があります。検索条件に基づいて、*検索条件の絞り込み*ページで製品の互換性を確認できます。このトピックでは、IMTの使用方法について簡単に説明します。

結果は*結果*ページで確認できます。このツールを使用して、コンポーネントの検索、選択、構築条件の作成、製品の互換性の表示を行うことができます。

次のタスクを実行できます。

[cols="25,65"]
|===
| 使用するページ | 実行できるタスク 


| 条件を入力 | 検索条件を入力し、ソリューション、コンポーネント、構成、カテゴリを検索します。ソリューション名がわかっている場合は、* ONTAP SAN Host Simplified *または* Solution Search *機能を使用してソリューションを検索できます。コンポーネント名がわかっている場合は、* List and Find *または* Advanced Search *機能を使用してコンポーネントを検索できます。 


| 検索条件の絞り込み | 製品の互換性のあるソリューション、コンポーネント、構成、カテゴリについて、より明確な「はい」または「いいえ」の答えを見つけてください。最初のページに入力した初期条件を、*[基準の変更]*または*別の方法を試してください*を使用して変更することができます。各カテゴリのコンポーネントにフィルタを適用して、製品に最適な構成を見つけます。[すべてクリア（Clear All）]または[元に戻す（Undo）]アイコンを使用して適用したフィルタを削除します。 


| 結果 | 2ページ目の* Continue *、*>*アイコン、またはスプリッタをクリックした後、* Results *ページを表示します。構成のコンポーネント、メモ、履歴の詳細の表示、検索結果のソート、選択した検索条件の表示、検索条件の変更、検索結果のフィルタリング、およびMicrosoft Excelシートへの検索結果のエクスポートを行うことができます。 
|===


== Interoperability Matrix Toolのホームページを使用する

Interoperability Matrix Tool（IMT）のホームページでは、* ONTAP SANホストの簡易化*、*ソリューションの検索、リストと検索*、*高度な検索*を使用できます。

* Set as Default * starを使用して、これらのオプションをデフォルト検索として設定できます。いずれかのオプションをクリックすると、該当するページが開き、互換性のある構成が表示されます。


NOTE: 以前に保存した検索を検索するには、*保存した検索*メニューを使用します。必要な構成が見つからない場合は、[*Can Not Find Config?*]メニューをクリックして問題を報告してください。
