---
sidebar: sidebar 
permalink: working-with-list-and-find.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network, list, find 
summary: 決定。 
---
= リストと検索の操作
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
構成要素のリストと検索（List and Find）作業領域では、構成要素に最適な構成を表示できます。



== タスクの内容

左側の*コンポーネントエクスプローラ*パネルを使用して、選択したコンポーネントの構成を表示します。右側のパネルにはソリューションが表示されます。各タブには、ストレージソリューションと、選択したコンポーネントを使用する構成の数が表示されます。List and Find Component Workare*の緑の* Logic *トグルボタンがまたはに設定されている場合、単一のコンポーネントを含む構成を持つソリューションを検索できます。緑の*ロジック*トグルボタンが*および*に設定されている場合、選択したすべての構成要素を含む構成を含むソリューションを検索できます。同じコンポーネントタイプ内で複数のコンポーネントが選択されている場合、ボタンは*または*に設定されます。



== 手順

. ホームページで*[リストと検索]*をクリックします。
. *コンポーネントエクスプローラ*でコンポーネント名を検索するか、選択範囲を展開して*リストとコンポーネントの検索作業領域*にコンポーネントを追加します。
+

NOTE: [リスト（List）]および[コンポーネントの検索（Find Component Workarea）]*にコンポーネントを追加した後、[次へ（Next）]*をクリックする前に、特定の有効なソリューションを選択できますExcelスプレッドシートまたはPDFでは、一度に1つのソリューションに対して最大3000行をエクスポートすることもできます。

. [次へ]*をクリックすると、*[結果]*ページに複数のソリューションの構成でコンポーネントが使用されている場所が表示されます。コンポーネントのリストに最も互換性のある構成が表示されます。

