---
sidebar: sidebar 
permalink: working-with-ontap-san-host-solutions-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: ONTAPバージョンとフラッシュまたはファブリックストレージバージョンの組み合わせの互換性を確認します。関連するコンポーネントごとに互換性検索をさらに絞り込むことができます。 
---
= ONTAP SANホストの簡易検索との連携
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAPバージョンとフラッシュまたはファブリックストレージバージョンの組み合わせの互換性を確認します。関連する各コンポーネントの互換性検索をさらに絞り込むことができます。



== タスクの内容

SAN上のフラッシュストレージデバイスまたはファブリックストレージデバイスと、使用するONTAPバージョンおよびその他の関連コンポーネントとの互換性を確認できます。*エキスパートビュー*または*初心者ビュー*のいずれかを選択できます。


NOTE: [デフォルトに設定]*オプションをクリックすると、IMTを開くたびに* ONTAP SAN Host Simplified *検索が自動的に開きます。



== 手順

. ホームページで* ONTAP SAN Host Simplified *をクリックします。
. 使用するビューを選択します。
+
.. 詳細な条件オプションを表示するには、*エキスパートビュー*をクリックします。
.. [ガイド付き表示（Guided view）]*をクリックして、簡略化された条件オプションとガイド付き条件オプション


. [初心者向けビュー]*で、表示されている検索条件オプションを選択します。
+
.. 選択せずに次の構成部品に移動するには、*スキップ*をクリックします。必要に応じて*[スキップ解除]*をクリックすると、コンポーネントに戻ることができます。
.. 完了したら、*[結果を表示]*をクリックして、検索条件でサポートされている構成を確認します。


. *エキスパートビュー*で、さまざまな構成要素に使用する検索条件を選択します。選択するたびに残りの条件が調整されるため、左から右に移動することをお勧めします。コンポーネントごとに選択する必要はありません。
+
.. 完了したら、*[結果を表示]*をクリックして、検索条件でサポートされている構成を確認します。


. また、* ONTAP SAN Host Simplified *の一部として、次の操作を実行することもできます。
+
.. ブックアイコンをクリックすると、選択したポリシーとガイドラインが表示されます。
.. チェーンアイコンをクリックすると、他のユーザーと共有できる共有可能なURLが生成されます。
.. [元に戻す（Undo）]アイコンを選択すると、すべての選択がクリアされ、再度開始されます。


. 結果画面では、次の操作を実行できます。
+
.. 構成に関する詳細、アラート、および通知情報を表示します。
.. この検索をお気に入りにするには、星のアイコンをクリックします。設定に名前を付けて説明します。これは保存された検索になり、*保存された検索*メニューから表示できます。ここで構成をサブスクライブすることもできます。これにより、変更が行われたときに通知が送信されます。購読している場合は、*購読*メニューにも表示されます。
.. [Build End to End View]にカーソルを合わせると、サポートされているその他のソリューションが表示されます。
.. 構成部品を変更し、他の互換性オプションを確認するには、* What If *をクリックします。



