---
sidebar: sidebar 
permalink: working-with-solution-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: 'さまざまなストレージソリューションを検索したり、検索条件にソリューションを追加または削除したりできます。[ソリューションの検索]ページ内の検索テキストボックスを使用して、特定のソリューションを検索できます。アクセス頻度の高いソリューションは、[ソリューション検索]フィールドに表示されます。' 
---
= ソリューション検索の操作
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
さまざまなストレージソリューションを検索したり、検索条件にソリューションを追加または削除したりできます。[ソリューションの検索]ページ内の検索テキストボックスを使用して、特定のソリューションを検索できます。アクセス頻度の高いソリューションは、*[ソリューション検索]*フィールドに表示されます。



== タスクの内容

[ソリューション検索]ページには、[ソリューションカタログ]タブと[マッピングアシスタント]タブがあります。[マッピングアシスタント]タブで、*[カテゴリ別マップ]*または*[ソリューション別マップ]*のいずれかを選択すると、選択したソリューションのカテゴリを表示できます。



=== ソリューションカタログ

*ソリューションカタログ*タブでは、フィルタバーを使用して*フィルタソリューション*を実行できます。

また、必要に応じて*[Include PVR Required]、[EOS]、[Obsolete configurations]*を選択することもできます。



=== マッピングアシスタント

次の2種類の作業領域モードがあります。

* *カテゴリ別マップ*：リストされたカテゴリからカテゴリを選択し、選択したカテゴリを含むすべてのソリューションを有効にすることができます。有効なソリューションはリストの一番上に表示されます。1つまたは複数の有効なソリューションを選択して追加できます。[カテゴリの検索]テキストボックスを使用して、特定のカテゴリを検索できます。
* *ソリューション別マップ*：リストされたソリューションからソリューションを選択し、リストの一番上に有効なソリューションを表示して、選択されたソリューションを含むすべてのソリューションを有効にすることができます。1つまたは複数の有効なソリューションを選択して追加できます。[検索ソリューション]テキストボックスを使用して、特定のカテゴリを検索できます。


また、必要に応じて*[Include PVR Required]、[EOS]、[Obsolete configurations]*を選択することもできます。

完了すると、*[選択したストレージソリューション]*で選択した項目が表示されます。*[View Refine Search Criteria]*または*[Skip to Results]*をクリックします。



=== ガイド付き検索

*ガイド付き検索*は、ソリューションを選択すると有効になります。*ガイド付き検索*には、条件をさらに絞り込むためのガイド付きワークフローが用意されています。



== 手順

. ホームページの*[ソリューション検索]*をクリックします。
. 使用するビューを選択します。
+
.. [エキスパートビュー（Expert view）]*をクリックすると、詳細な条件オプションが表示されます。
.. [ガイド付きビュー（Guided view）]*をクリックして、簡略化された条件とガイド付き条件のオプションを表示


. 初心者ビュー*で、表示されている検索条件オプションを選択します。
+
.. 選択せずに次の構成部品に移動するには、*スキップ*をクリックします。必要に応じて*[スキップ解除]*をクリックすると、コンポーネントに戻ることができます。
.. 最初の5つを選択したら、*[詳細を表示]*をクリックして、検索条件の絞り込みを続行します。前のビューに戻るには、*[表示を減らす]*をクリックします。
.. 完了したら、*[結果を表示]*をクリックして、検索条件でサポートされている構成を確認します。


. *エキスパートビュー*で、さまざまな構成要素に使用する検索条件を選択します。選択するたびに残りの条件が調整されるため、左から右に移動することをお勧めします。コンポーネントごとに選択する必要はありません。
+
.. 完了したら、*[結果を表示]*をクリックして、検索条件でサポートされている構成を確認します。


. また、*ソリューション検索*の一部として、次の操作を実行することもできます。
+
.. ブックアイコンをクリックすると、選択したポリシーとガイドラインが表示されます。
.. チェーンアイコンをクリックすると、他のユーザーと共有できる共有可能なURLが生成されます。
.. [元に戻す（Undo）]アイコンを選択すると、すべての選択がクリアされ、再度開始されます。


. 結果画面では、次の操作を実行できます。
+
.. 構成に関する詳細、アラート、および通知情報を表示します。
.. この検索をお気に入りにするには、星のアイコンをクリックします。設定に名前を付けて説明します。これは保存済み検索になり、[保存済み検索（Saved Search）]メニューから表示できます。ここで構成をサブスクライブすることもできます。これにより、変更が行われたときに通知が送信されます。購読している場合は、*購読*メニューにも表示されます。
.. [Build End to End View]にカーソルを合わせると、サポートされているその他のソリューションが表示されます。
.. 構成部品を変更し、他の互換性オプションを確認するには、* What If *をクリックします。



